"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
export default function AdminLogin(){
  const router=useRouter();const[method,setMethod]=useState<"code"|"password">("code");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const values=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/admin/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...values,method})});const body=await response.json();if(response.ok){router.push("/admin/dashboard");router.refresh();}else setError(body.error);setBusy(false);}
  function choose(next:"code"|"password"){setMethod(next);setError("");}
  return <div className="login-page"><section className="login-card"><p className="eyebrow">Harbor Time</p><h1>Manager sign in</h1><p className="muted">Open your company workspace securely.</p><div className="login-options" role="tablist" aria-label="Sign-in method"><button type="button" role="tab" aria-selected={method==="code"} className={method==="code"?"active":""} onClick={()=>choose("code")}>Access code</button><button type="button" role="tab" aria-selected={method==="password"} className={method==="password"?"active":""} onClick={()=>choose("password")}>Email &amp; password</button></div><form className="form-stack" onSubmit={submit}>{method==="code"?<><label>Company code<input name="companyCode" inputMode="text" autoComplete="organization" maxLength={32} required/></label><label>Manager access code<input name="accessCode" type="password" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{4,8}" minLength={4} maxLength={8} required/><small>Enter your 4–8 digit manager code.</small></label></>:<><label>Email<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" minLength={8} required/></label></>}{error&&<p className="alert error" role="alert">{error}</p>}<button disabled={busy} className="button primary">{busy?"Signing in…":"Sign in"}</button></form></section></div>;
}
