import { createHash, randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import bcrypt from "bcryptjs";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { beforeAll, describe, expect, it } from "vitest";

const url=process.env.SUPABASE_TEST_URL; const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY; const anonKey=process.env.SUPABASE_TEST_ANON_KEY;
const enabled=Boolean(url&&serviceKey&&anonKey);
describe.skipIf(!enabled)("Supabase production transactions",()=>{
  let admin:SupabaseClient;let manager:SupabaseClient;let companyId:string;let employeeId:string;let worksiteId:string;let tokenHash:string;let completedEntryId:string;
  const rpc=(action:string,key=randomUUID(),location:Record<string,unknown>={latitude:37.7955,longitude:-122.2787,accuracy_meters:8,permission_status:"GRANTED"})=>admin.rpc("employee_clock_action",{p_token_hash:tokenHash,p_action:action,p_worksite_id:worksiteId,p_idempotency_key:key,p_client_timestamp:new Date().toISOString(),p_latitude:location.latitude??null,p_longitude:location.longitude??null,p_accuracy_meters:location.accuracy_meters??null,p_permission_status:location.permission_status??"NOT_REQUESTED",p_source:"EMPLOYEE_WEB",p_device_metadata:{test:true}});
  beforeAll(async()=>{
    admin=createClient(url!,serviceKey!,{auth:{persistSession:false}});companyId=randomUUID();employeeId=randomUUID();worksiteId=randomUUID();const code=`TEST-${randomUUID()}`;
    expect((await admin.from("companies").insert({id:companyId,name:"Integration Company",legal_name:"Integration Company",display_name:"Integration Company",code,pay_frequency:"WEEKLY"})).error).toBeNull();
    expect((await admin.from("employees").insert({id:employeeId,company_id:companyId,employee_number:"E1",preferred_name:"Integration Employee",pin_hash:await bcrypt.hash("7531",10)})).error).toBeNull();
    expect((await admin.from("worksites").insert({id:worksiteId,company_id:companyId,name:"Test Site",address_line_1:"1 Test Way",city:"Oakland",state:"CA",postal_code:"94607",timezone:"America/Los_Angeles",latitude:37.7955,longitude:-122.2787,location_mode:"FLAG"})).error).toBeNull();
    expect((await admin.from("employee_worksites").insert({company_id:companyId,employee_id:employeeId,worksite_id:worksiteId})).error).toBeNull();
    tokenHash=createHash("sha256").update(randomUUID()).digest("hex");expect((await admin.rpc("create_employee_session",{p_employee_id:employeeId,p_token_hash:tokenHash,p_expires_at:new Date(Date.now()+3600000).toISOString()})).error).toBeNull();
    const email=`manager-${randomUUID()}@example.test`;const password=`T!${randomUUID()}a9`;const created=await admin.auth.admin.createUser({email,password,email_confirm:true});expect(created.error).toBeNull();expect((await admin.from("company_users").insert({company_id:companyId,user_id:created.data.user!.id,role:"MANAGER"})).error).toBeNull();manager=createClient(url!,anonKey!,{auth:{persistSession:false}});expect((await manager.auth.signInWithPassword({email,password})).error).toBeNull();
  },30000);
  it("looks up a hashed PIN candidate and records lockout state",async()=>{const candidate=await admin.rpc("employee_login_candidate",{p_company_code:(await admin.from("companies").select("code").eq("id",companyId).single()).data!.code,p_employee_number:"E1"});expect(candidate.error).toBeNull();expect(await bcrypt.compare("7531",candidate.data[0].pin_hash)).toBe(true);for(let i=0;i<5;i++)await admin.rpc("record_employee_login_attempt",{p_employee_id:employeeId,p_success:false});const locked=await admin.rpc("employee_login_candidate",{p_company_code:(await admin.from("companies").select("code").eq("id",companyId).single()).data!.code,p_employee_number:"E1"});expect(locked.data[0].pin_locked).toBe(true);await admin.from("employees").update({failed_pin_attempts:0,pin_locked_until:null}).eq("id",employeeId);});
  it("resolves, expires and revokes hashed sessions",async()=>{expect((await admin.rpc("resolve_employee_session",{p_token_hash:tokenHash})).data[0].employee_id).toBe(employeeId);const revokedHash=createHash("sha256").update(randomUUID()).digest("hex");await admin.rpc("create_employee_session",{p_employee_id:employeeId,p_token_hash:revokedHash,p_expires_at:new Date(Date.now()+3600000).toISOString()});await admin.rpc("revoke_employee_session",{p_token_hash:revokedHash});expect((await admin.rpc("resolve_employee_session",{p_token_hash:revokedHash})).data).toHaveLength(0);const expiredHash=createHash("sha256").update(randomUUID()).digest("hex");expect((await admin.from("employee_sessions").insert({company_id:companyId,employee_id:employeeId,token_hash:expiredHash,created_at:new Date(Date.now()-7200000).toISOString(),expires_at:new Date(Date.now()-3600000).toISOString()})).error).toBeNull();expect((await admin.rpc("resolve_employee_session",{p_token_hash:expiredHash})).data).toHaveLength(0);});
  it("serializes concurrent Clock In and makes retries idempotent",async()=>{const firstKey=randomUUID(),secondKey=randomUUID();const [first,second]=await Promise.all([rpc("CLOCK_IN",firstKey),rpc("CLOCK_IN",secondKey)]);expect([first.error,second.error].filter(Boolean)).toHaveLength(1);const winningKey=first.error?secondKey:firstKey;const duplicate=await rpc("CLOCK_IN",winningKey);expect(duplicate.error).toBeNull();expect(duplicate.data.duplicate).toBe(true);completedEntryId=(await admin.from("time_entries").select("id").eq("employee_id",employeeId).eq("status","OPEN").single()).data!.id;});
  it("enforces break state and Clock Out rules",async()=>{expect((await rpc("BREAK_START")).error).toBeNull();expect((await rpc("BREAK_START")).error).not.toBeNull();expect((await rpc("CLOCK_OUT")).error).not.toBeNull();expect((await rpc("BREAK_END")).error).toBeNull();expect((await rpc("CLOCK_OUT")).error).toBeNull();});
  it("persists completed records across a new server process",()=>{const script=`import{createClient}from'@supabase/supabase-js';const c=createClient(process.env.TEST_URL,process.env.TEST_KEY,{auth:{persistSession:false}});const{data,error}=await c.from('time_entries').select('status').eq('id',process.env.ENTRY_ID).single();if(error||data.status!=='COMPLETED')process.exit(1);`;expect(()=>execFileSync(process.execPath,["--input-type=module","-e",script],{cwd:process.cwd(),env:{...process.env,TEST_URL:url!,TEST_KEY:serviceKey!,ENTRY_ID:completedEntryId},stdio:"pipe"})).not.toThrow();});
  it("enforces STRICT, FLAG and OPTIONAL location modes",async()=>{await admin.from("worksites").update({location_mode:"STRICT"}).eq("id",worksiteId);expect((await rpc("CLOCK_IN",randomUUID(),{permission_status:"DENIED"})).error).not.toBeNull();await admin.from("worksites").update({location_mode:"FLAG"}).eq("id",worksiteId);expect((await rpc("CLOCK_IN",randomUUID(),{permission_status:"DENIED"})).error).toBeNull();await admin.from("worksites").update({location_mode:"OPTIONAL"}).eq("id",worksiteId);expect((await rpc("CLOCK_OUT",randomUUID(),{permission_status:"NOT_REQUESTED"})).error).toBeNull();});
  it("prevents anonymous and cross-company reads through RLS",async()=>{const anonymous=createClient(url!,anonKey!,{auth:{persistSession:false}});const blocked=await anonymous.from("time_entries").select("id");expect(blocked.data??[]).toEqual([]);const visible=await manager.from("time_entries").select("company_id");expect(visible.error).toBeNull();expect(visible.data).not.toBeNull();expect(visible.data!.every(row=>row.company_id===companyId)).toBe(true);});
  it("authorizes managers, rejects non-managers, and preserves audited edits",async()=>{const entry=(await admin.from("time_entries").select("id,clock_in_at,clock_out_at").eq("id",completedEntryId).single()).data!;const outsiderEmail=`outsider-${randomUUID()}@example.test`;const outsiderPassword=`T!${randomUUID()}z8`;await admin.auth.admin.createUser({email:outsiderEmail,password:outsiderPassword,email_confirm:true});const outsider=createClient(url!,anonKey!,{auth:{persistSession:false}});await outsider.auth.signInWithPassword({email:outsiderEmail,password:outsiderPassword});expect((await outsider.rpc("approve_time_entry",{p_entry_id:entry.id,p_approved:true,p_note:null})).error).not.toBeNull();expect((await manager.rpc("approve_time_entry",{p_entry_id:entry.id,p_approved:true,p_note:"Reviewed"})).error).toBeNull();const before=(await admin.from("time_events").select("id").eq("time_entry_id",entry.id)).data!.length;expect((await manager.rpc("manager_edit_time_entry",{p_entry_id:entry.id,p_clock_in_at:entry.clock_in_at,p_clock_out_at:entry.clock_out_at,p_breaks:null,p_reason:"Verified correction test"})).error).toBeNull();const after=(await admin.from("time_events").select("event_type,original_values").eq("time_entry_id",entry.id)).data!;expect(after.length).toBeGreaterThan(before);expect(after.some(event=>event.event_type==="MANAGER_EDIT"&&event.original_values)).toBe(true);expect((await admin.from("time_events").update({reason:"tamper"}).eq("time_entry_id",entry.id)).error).not.toBeNull();});
});
