"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { BriefcaseBusiness,KeyRound,MapPinned,Plus,UsersRound } from "lucide-react";

type Worksite={id:string;name:string;status:string};
type Team={id:string;name:string;description:string|null;status:string};
type Member={id:string;employee_number:string;preferred_name:string;status:string;worksites:string[];assignedWorksiteIds:string[];teamGroupIds:string[];teamNames:string[];currentState:string;completedShifts:number;approvedMinutes:number;lastShiftAt:string|null};
type Props={members:Member[];worksites:Worksite[];teams:Team[]};

async function send(url:string,method:string,payload:unknown){const response=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error??"The request could not be completed.");return body;}

export function EmployeeManagement({members,worksites,teams}:Props){
  const router=useRouter();const[message,setMessage]=useState("");const[busy,setBusy]=useState("");
  async function run(key:string,action:()=>Promise<unknown>,success:string){setBusy(key);setMessage("");try{await action();setMessage(success);router.refresh();return true;}catch(error){setMessage(error instanceof Error?error.message:"The request could not be completed.");return false;}finally{setBusy("");}}
  async function createEmployee(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const saved=await run("create-employee",()=>send("/api/admin/employees","POST",{employeeNumber:data.get("employeeNumber"),preferredName:data.get("preferredName"),pin:data.get("pin"),worksiteIds:data.getAll("worksiteIds"),teamGroupIds:data.getAll("teamGroupIds")}),"Employee created.");if(saved)form.reset();}
  async function createTeam(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const saved=await run("create-team",()=>send("/api/admin/teams","POST",{name:data.get("name"),description:data.get("description"),status:"ACTIVE"}),"Team group created.");if(saved)form.reset();}
  return <>
    {message&&<p className={`alert ${message.endsWith("created.")||message.endsWith("saved.")||message.endsWith("reset.")?"success":"error"}`} role="status">{message}</p>}
    <section className="management-grid">
      <form className="admin-card management-form" onSubmit={createEmployee}><div className="management-heading"><Plus/><div><h2>Add employee</h2><p>Create secure clock access and initial assignments.</p></div></div><div className="two-columns"><label>Employee number<input name="employeeNumber" maxLength={32} required/></label><label>Preferred name<input name="preferredName" maxLength={80} required/></label></div><label>Initial PIN<input name="pin" type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{4,8}" minLength={4} maxLength={8} required/><small>4–8 digits. The PIN is hashed before storage.</small></label><AssignmentChecks worksites={worksites.filter((item)=>item.status==="ACTIVE")} teams={teams.filter((item)=>item.status==="ACTIVE")}/><button className="button primary" disabled={Boolean(busy)}>{busy==="create-employee"?"Creating…":"Create employee"}</button></form>
      <section className="admin-card management-form"><div className="management-heading"><UsersRound/><div><h2>Team groups</h2><p>Organize employees without changing tenant access.</p></div></div><form className="inline-team-form" onSubmit={createTeam}><label>Team name<input name="name" maxLength={80} required/></label><label>Description<textarea name="description" maxLength={300}/></label><button className="button secondary" disabled={Boolean(busy)}>{busy==="create-team"?"Creating…":"Create team"}</button></form><div className="team-editor-list">{teams.map((team)=><details key={team.id}><summary><span className={team.status==="ACTIVE"?"":"inactive"}>{team.name}</span><small>{team.status}</small></summary><form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);void run(`team-${team.id}`,()=>send(`/api/admin/teams/${team.id}`,"PATCH",{name:data.get("name"),description:data.get("description"),status:data.get("status")}),"Team group saved.");}}><label>Name<input name="name" defaultValue={team.name} required/></label><label>Description<textarea name="description" defaultValue={team.description??""}/></label><label>Status<select name="status" defaultValue={team.status}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><button className="button secondary" disabled={Boolean(busy)}>{busy===`team-${team.id}`?"Saving…":"Save team"}</button></form></details>)}</div></section>
    </section>
    <section className="admin-card employee-management-list"><div className="card-header"><div><h2>Employees</h2><p>Profile, PIN, worksite, and team controls</p></div><span>{members.length} records</span></div>{members.length===0?<div className="empty-state">No employees are registered.</div>:members.map((member)=><details className="employee-manage-row" key={member.id}><summary><span className="mini-avatar">{member.preferred_name.slice(0,2).toUpperCase()}</span><span><strong>{member.preferred_name}</strong><small>{member.employee_number} · {member.currentState.replace("_"," ")}</small></span><span><MapPinned/> {member.worksites.join(", ")||"No worksite"}</span><span><UsersRound/> {member.teamNames.join(", ")||"No team"}</span><b>{member.status}</b></summary><div className="employee-controls">
        <form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);void run(`profile-${member.id}`,()=>send(`/api/admin/employees/${member.id}`,"PATCH",{action:"profile",preferredName:data.get("preferredName"),status:data.get("status")}),"Employee profile saved.");}}><h3><BriefcaseBusiness/> Profile</h3><label>Preferred name<input name="preferredName" defaultValue={member.preferred_name} required/></label><label>Status<select name="status" defaultValue={member.status}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><button className="button secondary" disabled={Boolean(busy)}>{busy===`profile-${member.id}`?"Saving…":"Save profile"}</button></form>
        <form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);void run(`pin-${member.id}`,()=>send(`/api/admin/employees/${member.id}`,"PATCH",{action:"resetPin",pin:data.get("pin")}),"Employee PIN reset.");}}><h3><KeyRound/> Reset PIN</h3><p>Resetting the PIN signs the employee out of existing sessions.</p><label>New PIN<input name="pin" type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{4,8}" minLength={4} maxLength={8} required/></label><button className="button secondary" disabled={Boolean(busy)}>{busy===`pin-${member.id}`?"Resetting…":"Reset PIN"}</button></form>
        <form className="assignment-control" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);void run(`assign-${member.id}`,()=>send(`/api/admin/employees/${member.id}`,"PATCH",{action:"assignments",worksiteIds:data.getAll("worksiteIds"),teamGroupIds:data.getAll("teamGroupIds")}),"Employee assignments saved.");}}><h3><MapPinned/> Assignments</h3><AssignmentChecks worksites={worksites.filter((item)=>item.status==="ACTIVE")} teams={teams.filter((item)=>item.status==="ACTIVE")} selectedWorksites={member.assignedWorksiteIds} selectedTeams={member.teamGroupIds}/><button className="button primary" disabled={Boolean(busy)}>{busy===`assign-${member.id}`?"Saving…":"Save assignments"}</button></form>
      </div></details>)}</section>
  </>;
}

function AssignmentChecks({worksites,teams,selectedWorksites=[],selectedTeams=[]}:{worksites:Worksite[];teams:Team[];selectedWorksites?:string[];selectedTeams?:string[]}){return <div className="assignment-groups"><fieldset><legend>Worksites</legend>{worksites.length===0?<small>No active worksites.</small>:worksites.map((site)=><label className="check-label" key={site.id}><input type="checkbox" name="worksiteIds" value={site.id} defaultChecked={selectedWorksites.includes(site.id)}/>{site.name}</label>)}</fieldset><fieldset><legend>Teams</legend>{teams.length===0?<small>No active team groups.</small>:teams.map((team)=><label className="check-label" key={team.id}><input type="checkbox" name="teamGroupIds" value={team.id} defaultChecked={selectedTeams.includes(team.id)}/>{team.name}</label>)}</fieldset></div>}
