"use client";
import { FormEvent, useState } from "react";
import { Check, Clock3, X } from "lucide-react";

export function TimesheetReviewPanel({ entryId, clockInAt, clockOutAt }: { entryId: string; clockInAt: string; clockOutAt: string | null }) {
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function review(decision:"APPROVED"|"REJECTED", note:string) { setBusy(true); const response=await fetch(`/api/admin/timesheets/${entryId}/review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision,note})}); const body=await response.json(); setMessage(response.ok?`Timesheet ${decision.toLowerCase()}.`:body.error); setBusy(false); }
  async function edit(event:FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form=new FormData(event.currentTarget); const response=await fetch(`/api/admin/timesheets/${entryId}/edit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clockInAt:new Date(String(form.get("clockInAt"))).toISOString(),clockOutAt:new Date(String(form.get("clockOutAt"))).toISOString(),reason:form.get("reason")})}); const body=await response.json(); setMessage(response.ok?"Audited correction saved.":body.error); setBusy(false); }
  const local=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):"";
  return <section className="admin-card detail-card"><h2>Manager review</h2><form className="form-stack" onSubmit={(event)=>{event.preventDefault(); const note=String(new FormData(event.currentTarget).get("note")??""); void review("APPROVED",note);}}><label>Manager note<textarea name="note" placeholder="Optional note visible to the employee"/></label><div className="review-actions"><button disabled={busy} className="button approve"><Check/>Approve</button><button disabled={busy} type="button" className="button reject" onClick={(event)=>{const form=event.currentTarget.closest("form"); void review("REJECTED",String(form?new FormData(form).get("note")??"":""));}}><X/>Request correction</button></div></form><hr/><h3>Correct recorded time</h3><p className="muted">A reason is required. Original values remain in the event and audit history.</p><form className="form-stack" onSubmit={edit}><div className="two-columns"><label>Clock in<input name="clockInAt" type="datetime-local" defaultValue={local(clockInAt)} required/></label><label>Clock out<input name="clockOutAt" type="datetime-local" defaultValue={local(clockOutAt)} required/></label></div><label>Reason for correction<textarea name="reason" minLength={3} required/></label><button disabled={busy} className="button secondary"><Clock3/>Save audited correction</button></form>{message&&<p className={`alert ${message.includes("saved")||message.includes("approved")?"success":"error"}`} role="status">{message}</p>}</section>;
}
