import { randomUUID } from "node:crypto";
import bcrypt from "bcryptjs";
import { assertTransition, calculateDurations, deriveState, openBreak } from "@/lib/time-clock";
import { hashSessionToken, lockoutUntil } from "@/lib/security";
import type { ClockAction, TimeEntry } from "@/lib/types";

const companyId="10000000-0000-4000-8000-000000000001";export const employeeId="10000000-0000-4000-8000-000000000002";export const worksiteId="10000000-0000-4000-8000-000000000003";
type Employee={id:string;companyId:string;number:string;pinHash:string;failedAttempts:number;lockedUntil:Date|null};type Session={employeeId:string;tokenHash:string;expiresAt:Date;revoked?:boolean};type Event={type:ClockAction;serverTimestamp:Date;idempotencyKey:string};
export const store:{employees:Employee[];sessions:Session[];entries:TimeEntry[];events:Event[]}={employees:[],sessions:[],entries:[],events:[]};
const pepper="test-pepper-with-more-than-thirty-two-characters";
export function resetStoreForTests(){store.employees=[{id:employeeId,companyId,number:"T-1",pinHash:bcrypt.hashSync("7531",8),failedAttempts:0,lockedUntil:null}];store.sessions=[];store.entries=[];store.events=[];}
export function authenticateEmployee(company:string,number:string,pin:string,now=new Date()){const employee=company==="TEST"?store.employees.find(item=>item.number===number):undefined;if(!employee||(employee.lockedUntil&&employee.lockedUntil>now)||!bcrypt.compareSync(pin,employee.pinHash)){if(employee){employee.failedAttempts+=1;employee.lockedUntil=lockoutUntil(employee.failedAttempts,now);}throw new Error("The sign-in details could not be verified. Try again later.");}employee.failedAttempts=0;employee.lockedUntil=null;const token=randomUUID();store.sessions.push({employeeId:employee.id,tokenHash:hashSessionToken(token,pepper),expiresAt:new Date(now.getTime()+8*3600000)});return{token};}
export function employeeFromToken(token:string,now=new Date()){const session=store.sessions.find(item=>item.tokenHash===hashSessionToken(token,pepper)&&!item.revoked);if(!session||session.expiresAt<=now)return null;return store.employees.find(item=>item.id===session.employeeId)??null;}
export function performAction({employeeId:subject,action,idempotencyKey,now=new Date()}:{employeeId:string;worksiteId:string;action:ClockAction;location:unknown;idempotencyKey:string;now?:Date}){if(store.events.some(item=>item.idempotencyKey===idempotencyKey))return;const entry=store.entries.find(item=>item.employeeId===subject&&!item.clockOutAt);assertTransition(deriveState(entry),action);let current=entry;if(action==="CLOCK_IN"){current={id:randomUUID(),companyId,employeeId:subject,worksiteId,clockInAt:now,breaks:[],approvalStatus:"PENDING"};store.entries.push(current);}else if(!current)throw new Error("No open time entry");else if(action==="BREAK_START"){current.breaks.push({id:randomUUID(),type:"UNPAID",startedAt:now});}else if(action==="BREAK_END"){const active=openBreak(current);if(!active)throw new Error("No active break");active.endedAt=now;}else{current.clockOutAt=now;const durations=calculateDurations(current,now);current.totalWorkMinutes=durations.netWorkMinutes;current.totalBreakMinutes=durations.totalBreakMinutes;}store.events.push({type:action,serverTimestamp:now,idempotencyKey});}
resetStoreForTests();
